SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, fp.PRICE * sum(fo.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT fp
join FOOD_ORDER fo
on fp.PRODUCT_ID = fo.PRODUCT_ID
where YEAR(fo.PRODUCE_DATE) = 2022
and MONTH(fo.PRODUCE_DATE) = 5
group by fp.PRODUCT_ID
order by TOTAL_SALES desc, fp.PRODUCT_ID asc