select
    sum(HG.SCORE) as SCORE,
    HE.EMP_NO as EMP_NO,
    HE.EMP_NAME as EMP_NAME,
    HE.POSITION as POSITION,
    HE.EMAIL as EMAIL
FROM
    HR_EMPLOYEES HE
INNER JOIN
    HR_GRADE HG on HE.EMP_NO = HG.EMP_NO
WHERE
    HG.YEAR = 2022
GROUP BY
    HE.EMP_NO
ORDER BY
    sum(HG.SCORE) desc
LIMIT 1;