SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD UGB
join USED_GOODS_REPLY UGR
on UGB.BOARD_ID = UGR.BOARD_ID
where YEAR(UGB.CREATED_DATE) = 2022
and MONTH(UGB.CREATED_DATE) = 10
order by UGR.CREATED_DATE ASC, UGB.TITLE ASC
